### PR TITLE
GO sorting algo

### PR DESCRIPTION
**Pull request by mrDarkk**
bubble sort , insertion sort , merge sort, quick sort added

### CODE REVIEW

**Comment by huangyz0918** [comment]
Please remove the `.DS_Store`. @mrDarkk

**Comment by mrDarkk** [comment]
#25

**Comment by mrDarkk** [comment]
Please Check @huangyz0918

**Comment by huangyz0918** [comment]
I said: Please remove the .DS_Store. @mrDarkk, thanks.

**Pull request merged**
